# Generated by Django 4.0.2 on 2022-03-01 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_alter_agent_photo'),
        ('inquiries', '0002_inquiry_date_inquiry_alter_inquiry_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agent'),
        ),
    ]
