# Generated by Django 4.0.2 on 2022-03-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='photo',
            field=models.ImageField(upload_to='photos/blocks/%Y/%m/%d/'),
        ),
    ]
